### ISSUE TITLE
Works in a browser too? 

### ISSUE THREAD

**Issue by paul-hammant** [LinusU/gopher-hcl#3]
I ask as the code example is for NodeJs

**Comment by LinusU** [comment]
It should work with Browserify, WebPack, or Rollup 👍 

I think adding UMD or similar files is the wrong approach, so would prefer not doing that...

**Comment by paul-hammant** [comment]
Well I'm really after the ability to GET and PUT a text resource from/to the server. I'm wanting a CR-delimited text format that's less noisy with diffs than JSON is (the client-side Vue.js app that I have now works perfectly with JSON except for diff noise in document history).  

TOML was a choice, I thought. But it was stymied by the way it saves multi-line arrays. See https://github.com/uiri/toml/issues/91. However, I've missed that the devs for that were busy referencing the issue in a series of commits, so I should investigate again.  

Not sure if you're going to see this or not, as you've closed the issue. Thanks for responding anyway.

**Comment by LinusU** [comment]
Maybe your diffs could be expressed with [JSON Patch](http://jsonpatch.com)?
