### ISSUE TITLE
Please rebuild and publish it for terraform 12

### ISSUE THREAD

**Issue by Ghost---Shadow** [LinusU/gopher-hcl#4]

**Comment by LinusU** [comment]
Should be fixed by 230db09, released as `0.2.0` 🚀

**Comment by Ghost---Shadow** [comment]
Doesnt seem to work. Tried it on this
https://github.com/hashicorp/terraform-aws-vault/blob/master/modules/private-tls-cert/main.tf

**Comment by LinusU** [comment]
Hmm, what error did you get?

**Comment by Ghost---Shadow** [comment]
It is not able to parse variables which are not `${something}`. It cannot parse terraform 12 syntax.
